"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type QuestionType = "text" | "textarea" | "single_choice" | "multiple_choice";
type Question = { id:string; question_text:string; question_type:QuestionType; is_required:boolean; sort_order:number; event_question_options:{option_text:string;sort_order:number}[] };

export default function EventQuestionsPage(){
  const {id}=useParams<{id:string}>();
  const [eventTitle,setEventTitle]=useState(""),[questions,setQuestions]=useState<Question[]>([]);
  const [text,setText]=useState(""),[type,setType]=useState<QuestionType>("text"),[required,setRequired]=useState(false),[options,setOptions]=useState(["",""]);
  const [saving,setSaving]=useState(false),[message,setMessage]=useState(""),[isError,setIsError]=useState(false);
  async function load(){const s=createClient(),[eventResult,questionResult]=await Promise.all([s.from("events").select("title").eq("id",id).maybeSingle(),s.from("event_questions").select("id,question_text,question_type,is_required,sort_order,event_question_options(option_text,sort_order)").eq("event_id",id).order("sort_order")]);if(eventResult.data)setEventTitle(eventResult.data.title);if(questionResult.error){setIsError(true);setMessage(`質問を取得できませんでした：${questionResult.error.message}`)}else setQuestions((questionResult.data??[])as Question[])}
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[id]);
  const hasOptions=type==="single_choice"||type==="multiple_choice";
  async function submit(e:FormEvent){e.preventDefault();const body=text.trim(),validOptions=options.map(x=>x.trim()).filter(Boolean);if(!body){setIsError(true);setMessage("質問内容を入力してください。");return}if(hasOptions&&validOptions.length<2){setIsError(true);setMessage("選択肢を2つ以上入力してください。");return}setSaving(true);setMessage("");const s=createClient(),{data,error}=await s.from("event_questions").insert({event_id:id,question_text:body,question_type:type,is_required:required,sort_order:questions.length+1}).select("id").single();if(error||!data){setIsError(true);setMessage(`質問を追加できませんでした：${error?.message??"不明なエラー"}`);setSaving(false);return}if(hasOptions){const{error:optionError}=await s.from("event_question_options").insert(validOptions.map((option_text,index)=>({question_id:data.id,option_text,sort_order:index+1})));if(optionError){await s.from("event_questions").delete().eq("id",data.id);setIsError(true);setMessage(`選択肢を追加できませんでした：${optionError.message}`);setSaving(false);return}}setText("");setType("text");setRequired(false);setOptions(["",""]);setIsError(false);setMessage("質問を追加しました。");await load();setSaving(false)}
  return <main className="min-h-screen bg-neutral-100 px-4 py-8 sm:px-6"><div className="mx-auto max-w-4xl"><Link href={`/admin/events/${id}`} className="text-sm font-bold text-neutral-600 underline">← イベント編集へ戻る</Link><header className="mt-6"><p className="text-sm font-bold text-blue-600">APPLICATION QUESTIONS</p><h1 className="mt-2 text-3xl font-black">質問管理</h1>{eventTitle&&<p className="mt-2 text-neutral-500">{eventTitle}</p>}</header>
  {message&&<p className={`mt-5 rounded-xl p-4 text-sm ${isError?"bg-red-50 text-red-700":"bg-green-50 text-green-700"}`}>{message}</p>}
  <div className="mt-7 grid gap-6 md:grid-cols-[1fr_1fr]"><form onSubmit={submit} className="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">質問を追加</h2><label className="mt-5 block text-sm font-bold">質問内容<input value={text} onChange={e=>setText(e.target.value)} className="mt-2 w-full rounded-xl border border-neutral-300 p-3"/></label><label className="mt-4 block text-sm font-bold">回答形式<select value={type} onChange={e=>setType(e.target.value as QuestionType)} className="mt-2 w-full rounded-xl border border-neutral-300 bg-white p-3"><option value="text">一行入力</option><option value="textarea">複数行入力</option><option value="single_choice">単一選択</option><option value="multiple_choice">複数選択</option></select></label><label className="mt-4 flex gap-2 text-sm font-bold"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>回答を必須にする</label>{hasOptions&&<div className="mt-4"><p className="text-sm font-bold">選択肢</p>{options.map((option,index)=><div key={index} className="mt-2 flex gap-2"><input value={option} onChange={e=>setOptions(current=>current.map((x,i)=>i===index?e.target.value:x))} placeholder={`選択肢${index+1}`} className="min-w-0 flex-1 rounded-xl border p-3"/><button type="button" disabled={options.length<=2} onClick={()=>setOptions(current=>current.filter((_,i)=>i!==index))} className="rounded-xl border px-3 text-red-600 disabled:opacity-30">削除</button></div>)}<button type="button" onClick={()=>setOptions([...options,""])} className="mt-3 text-sm font-bold text-blue-600">＋ 選択肢を追加</button></div>}<button disabled={saving} className="mt-6 w-full rounded-xl bg-blue-600 p-3 font-bold text-white disabled:bg-neutral-300">{saving?"追加中…":"質問を追加する"}</button></form>
  <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">登録済みの質問</h2><div className="mt-5 space-y-3">{questions.map((q,index)=><article key={q.id} className="rounded-xl border p-4"><p className="font-bold">{index+1}. {q.question_text}{q.is_required&&<span className="ml-2 text-xs text-red-600">必須</span>}</p><p className="mt-2 text-xs text-neutral-500">{formatType(q.question_type)}</p>{q.event_question_options?.length>0&&<ul className="mt-2 list-disc pl-5 text-sm text-neutral-600">{[...q.event_question_options].sort((a,b)=>a.sort_order-b.sort_order).map(x=><li key={x.sort_order}>{x.option_text}</li>)}</ul>}</article>)}{questions.length===0&&<p className="text-sm text-neutral-500">質問はまだありません。</p>}</div></section></div></div></main>;
}
function formatType(type:QuestionType){return {text:"一行入力",textarea:"複数行入力",single_choice:"単一選択",multiple_choice:"複数選択"}[type]}
