"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Character = { id: string; name: string; description: string | null; image_url: string | null; sort_order: number; is_active: boolean };
const empty = { name: "", description: "", image_url: "", sort_order: 0, is_active: true };

export default function AdminCharactersPage() {
  const [rows, setRows] = useState<Character[]>([]);
  const [form, setForm] = useState(empty);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  async function load() { const { data, error } = await createClient().from("voice_characters").select("id, name, description, image_url, sort_order, is_active").order("sort_order"); if (!error) setRows((data ?? []) as Character[]); }
  useEffect(() => { void load(); }, []);
  async function save(e: FormEvent) { e.preventDefault(); const supabase = createClient(); const values = { ...form, name: form.name.trim(), description: form.description.trim() || null, image_url: form.image_url.trim() || null, updated_at: new Date().toISOString() }; const { error } = editingId ? await supabase.from("voice_characters").update(values).eq("id", editingId) : await supabase.from("voice_characters").insert(values); setMessage(error ? error.message : "保存しました。"); if (!error) { setForm(empty); setEditingId(null); await load(); } }
  async function remove(id: string) { if (!confirm("このキャラクターを削除しますか？使用中の場合は削除できません。")) return; const { error } = await createClient().from("voice_characters").delete().eq("id", id); setMessage(error ? error.message : "削除しました。"); if (!error) await load(); }
  return <main className="min-h-screen bg-neutral-100 px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold text-blue-600">KOELABO</p><h1 className="mt-2 text-3xl font-black">キャラクター管理</h1><div className="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={save} className="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{editingId ? "キャラクター編集" : "新規キャラクター"}</h2><label className="mt-5 block text-sm font-bold">名前<input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-neutral-300 px-4 py-3"/></label><label className="mt-4 block text-sm font-bold">説明<textarea value={form.description} onChange={(e) => setForm({...form,description:e.target.value})} rows={4} className="mt-2 w-full rounded-xl border border-neutral-300 px-4 py-3"/></label><label className="mt-4 block text-sm font-bold">画像URL<input type="url" value={form.image_url} onChange={(e) => setForm({...form,image_url:e.target.value})} className="mt-2 w-full rounded-xl border border-neutral-300 px-4 py-3"/></label><label className="mt-4 block text-sm font-bold">表示順<input type="number" value={form.sort_order} onChange={(e) => setForm({...form,sort_order:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-neutral-300 px-4 py-3"/></label><label className="mt-4 flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({...form,is_active:e.target.checked})}/>公開する</label><button className="mt-6 w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">保存する</button>{editingId && <button type="button" onClick={() => {setEditingId(null);setForm(empty)}} className="mt-2 w-full rounded-xl border px-4 py-3">キャンセル</button>}{message && <p className="mt-3 text-sm">{message}</p>}</form><div className="space-y-4">{rows.map((row) => <article key={row.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><h2 className="font-bold">{row.name}</h2><p className="mt-1 text-sm text-neutral-500">{row.description || "説明なし"}</p><span className="mt-2 inline-block text-xs text-neutral-400">表示順 {row.sort_order} · {row.is_active ? "公開" : "非公開"}</span></div><div className="flex gap-2"><button onClick={() => {setEditingId(row.id);setForm({name:row.name,description:row.description??"",image_url:row.image_url??"",sort_order:row.sort_order,is_active:row.is_active})}} className="rounded-xl bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700">編集</button><button onClick={() => remove(row.id)} className="rounded-xl bg-red-50 px-4 py-2 text-sm font-bold text-red-700">削除</button></div></div></article>)}</div></div></div></main>;
}
